@startuml
left to right direction
rectangle toplevel{
()toplevel_io_a
()toplevel_io_b0
()toplevel_io_b1
()toplevel_io_b2
()toplevel_tmp
()toplevel_clk
()toplevel_reset
()toplevel_cp_clk
()toplevel_cp_reset
()toplevel_ap_clk
()toplevel_ap_reset
()toplevel_adc_clk
()toplevel_adc_reset
}
rectangle u_sub0{
()u_sub0_io_ai
()u_sub0_io_ao
()u_sub0_io_ai_regNext
()u_sub0_cp_clk
()u_sub0_cp_reset
}
rectangle u_sub1{
()u_sub1_io_ai
()u_sub1_io_ao
()u_sub1_io_a2
()u_sub1_io_ai_regNext
()u_sub1_area_tmp
()u_sub1_io_ai_regNext_1
()u_sub1_area_tmp2
()u_sub1_ap_clk
()u_sub1_ap_reset
()u_sub1_adc_clk
()u_sub1_adc_reset
}
u_sub0_io_ao-->toplevel_io_b0
u_sub1_io_ao-->toplevel_io_b1
u_sub1_io_a2-->toplevel_io_b2
toplevel_io_a-->toplevel_tmp
toplevel_io_a-->u_sub0_io_ai
u_sub0_io_ai_regNext-->u_sub0_io_ao
u_sub0_io_ai-->u_sub0_io_ai_regNext
toplevel_io_a-->u_sub1_io_ai
u_sub1_io_ai_regNext-->u_sub1_io_ao
u_sub1_area_tmp2-->u_sub1_io_a2
u_sub1_io_ai-->u_sub1_io_ai_regNext
u_sub1_io_ai-->u_sub1_area_tmp
u_sub1_io_ai-->u_sub1_io_ai_regNext_1
u_sub1_area_tmp-->u_sub1_area_tmp2
u_sub1_io_ai_regNext_1-->u_sub1_area_tmp2
@enduml