@startuml
left to right direction
rectangle toplevel{
()toplevel_din_valid
()toplevel_din_payload
()toplevel_dout_valid
()toplevel_dout_payload
()toplevel_flush
()toplevel_din_toStream_valid
()toplevel_din_toStream_ready
()toplevel_din_toStream_payload
()toplevel_smp_clk
()toplevel_smp_reset
()toplevel_clk
}
rectangle u_fifo_in{
()u_fifo_in__zz_1
()u_fifo_in_io_push_valid
()u_fifo_in_io_push_ready
()u_fifo_in_io_push_payload
()u_fifo_in_io_pop_valid
()u_fifo_in_io_pop_ready
()u_fifo_in_io_pop_payload
()u_fifo_in_io_pushOccupancy
()u_fifo_in_io_popOccupancy
()u_fifo_in_popToPushGray
()u_fifo_in_pushToPopGray
()u_fifo_in_pushCC_pushPtr
()u_fifo_in_pushCC_pushPtrPlus
()u_fifo_in_io_push_fire
()u_fifo_in_pushCC_pushPtrGray
()u_fifo_in_pushCC_popPtrGray
()u_fifo_in_pushCC_full
()u_fifo_in_io_push_fire_1
()u_fifo_in__zz_io_pushOccupancy
()u_fifo_in__zz_io_pushOccupancy_1
()u_fifo_in__zz_io_pushOccupancy_2
()u_fifo_in_smp_reset_syncronized
()u_fifo_in_popCC_popPtr
()u_fifo_in_popCC_popPtrPlus
()u_fifo_in_io_pop_fire
()u_fifo_in_popCC_popPtrGray
()u_fifo_in_popCC_pushPtrGray
()u_fifo_in_popCC_empty
()u_fifo_in_io_pop_fire_1
()u_fifo_in__zz_io_pop_payload
()u_fifo_in_io_pop_fire_2
()u_fifo_in__zz_io_popOccupancy
()u_fifo_in__zz_io_popOccupancy_1
()u_fifo_in__zz_io_popOccupancy_2
()u_fifo_in_smp_clk
()u_fifo_in_smp_reset
()u_fifo_in_clk
}
u_fifo_in_io_pop_valid-->toplevel_dout_valid
u_fifo_in_io_pop_payload-->toplevel_dout_payload
toplevel_din_valid-->toplevel_din_toStream_valid
u_fifo_in_io_push_ready-->toplevel_din_toStream_ready
toplevel_din_payload-->toplevel_din_toStream_payload
u_fifo_in_io_push_fire_1-->u_fifo_in__zz_1
toplevel_din_toStream_valid-->u_fifo_in_io_push_valid
u_fifo_in_pushCC_full-->u_fifo_in_io_push_ready
toplevel_din_toStream_payload-->u_fifo_in_io_push_payload
u_fifo_in_popCC_empty-->u_fifo_in_io_pop_valid
u_fifo_in__zz_io_pop_payload-->u_fifo_in_io_pop_payload
u_fifo_in_pushCC_pushPtr-->u_fifo_in_io_pushOccupancy
u_fifo_in__zz_io_pushOccupancy_2-->u_fifo_in_io_pushOccupancy
u_fifo_in__zz_io_pushOccupancy_1-->u_fifo_in_io_pushOccupancy
u_fifo_in__zz_io_pushOccupancy-->u_fifo_in_io_pushOccupancy
u_fifo_in_pushCC_popPtrGray-->u_fifo_in_io_pushOccupancy
u_fifo_in__zz_io_popOccupancy_2-->u_fifo_in_io_popOccupancy
u_fifo_in__zz_io_popOccupancy_1-->u_fifo_in_io_popOccupancy
u_fifo_in__zz_io_popOccupancy-->u_fifo_in_io_popOccupancy
u_fifo_in_popCC_pushPtrGray-->u_fifo_in_io_popOccupancy
u_fifo_in_popCC_popPtr-->u_fifo_in_io_popOccupancy
u_fifo_in_popCC_popPtrGray-->u_fifo_in_popToPushGray
u_fifo_in_pushCC_pushPtrGray-->u_fifo_in_pushToPopGray
u_fifo_in_pushCC_pushPtrPlus-->u_fifo_in_pushCC_pushPtr
u_fifo_in_io_push_fire_1-->u_fifo_in_pushCC_pushPtr
u_fifo_in_pushCC_pushPtr-->u_fifo_in_pushCC_pushPtrPlus
u_fifo_in_io_push_valid-->u_fifo_in_io_push_fire
u_fifo_in_io_push_ready-->u_fifo_in_io_push_fire
u_fifo_in_pushCC_pushPtrPlus-->u_fifo_in_pushCC_pushPtrGray
u_fifo_in_io_push_fire-->u_fifo_in_pushCC_pushPtrGray
popToPushGray_buffercc_io_dataOut-->u_fifo_in_pushCC_popPtrGray
u_fifo_in_pushCC_pushPtrGray-->u_fifo_in_pushCC_full
u_fifo_in_pushCC_popPtrGray-->u_fifo_in_pushCC_full
u_fifo_in_io_push_valid-->u_fifo_in_io_push_fire_1
u_fifo_in_io_push_ready-->u_fifo_in_io_push_fire_1
u_fifo_in_pushCC_popPtrGray-->u_fifo_in__zz_io_pushOccupancy
u_fifo_in__zz_io_pushOccupancy_1-->u_fifo_in__zz_io_pushOccupancy
u_fifo_in_pushCC_popPtrGray-->u_fifo_in__zz_io_pushOccupancy_1
u_fifo_in__zz_io_pushOccupancy_2-->u_fifo_in__zz_io_pushOccupancy_1
u_fifo_in_pushCC_popPtrGray-->u_fifo_in__zz_io_pushOccupancy_2
bufferCC_3_io_dataOut-->u_fifo_in_smp_reset_syncronized
u_fifo_in_popCC_popPtrPlus-->u_fifo_in_popCC_popPtr
u_fifo_in_io_pop_fire_2-->u_fifo_in_popCC_popPtr
u_fifo_in_popCC_popPtr-->u_fifo_in_popCC_popPtrPlus
u_fifo_in_io_pop_valid-->u_fifo_in_io_pop_fire
u_fifo_in_io_pop_ready-->u_fifo_in_io_pop_fire
u_fifo_in_popCC_popPtrPlus-->u_fifo_in_popCC_popPtrGray
u_fifo_in_io_pop_fire-->u_fifo_in_popCC_popPtrGray
pushToPopGray_buffercc_io_dataOut-->u_fifo_in_popCC_pushPtrGray
u_fifo_in_popCC_popPtrGray-->u_fifo_in_popCC_empty
u_fifo_in_popCC_pushPtrGray-->u_fifo_in_popCC_empty
u_fifo_in_io_pop_valid-->u_fifo_in_io_pop_fire_1
u_fifo_in_io_pop_ready-->u_fifo_in_io_pop_fire_1
u_fifo_in_io_pop_fire_1-->u_fifo_in__zz_io_pop_payload
u_fifo_in_popCC_popPtrPlus-->u_fifo_in__zz_io_pop_payload
u_fifo_in_popCC_popPtr-->u_fifo_in__zz_io_pop_payload
u_fifo_in_io_pop_valid-->u_fifo_in_io_pop_fire_2
u_fifo_in_io_pop_ready-->u_fifo_in_io_pop_fire_2
u_fifo_in_popCC_pushPtrGray-->u_fifo_in__zz_io_popOccupancy
u_fifo_in__zz_io_popOccupancy_1-->u_fifo_in__zz_io_popOccupancy
u_fifo_in_popCC_pushPtrGray-->u_fifo_in__zz_io_popOccupancy_1
u_fifo_in__zz_io_popOccupancy_2-->u_fifo_in__zz_io_popOccupancy_1
u_fifo_in_popCC_pushPtrGray-->u_fifo_in__zz_io_popOccupancy_2
@enduml